# Generated by Django 5.2.8 on 2025-11-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Trash Can',
                'verbose_name_plural': 'Trash Cans',
            },
        ),
        migrations.CreateModel(
            name='FillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.IntegerField(default=0, help_text='Fill level from 0 to 100')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trashcan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_records', to='garbageData.trashcan')),
            ],
            options={
                'verbose_name': 'Fill Record',
                'verbose_name_plural': 'Fill Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
