# Generated by Django 5.2.8 on 2025-11-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('can_map_coordinates', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FillRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fullness_percent', models.FloatField()),
                ('efpdc', models.FloatField(blank=True, null=True)),
                ('trash_can', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='garbageData.trashcan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
