# Generated by Django 5.2.8 on 2025-11-29 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillrecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Camera'), ('predicted', 'Predicted')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='trashcan',
            name='last_emptied',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time bin was emptied'),
        ),
    ]
