# Generated by Django 5.2.8 on 2025-11-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageData', '0002_fillrecord_source_trashcan_last_emptied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillrecord',
            name='fill_level',
            field=models.IntegerField(default=0, help_text='Fill level (0-100+, >100 means overflowing)'),
        ),
    ]
