# Generated by Django 5.2.8 on 2025-11-30 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageData', '0004_alter_fillrecord_fill_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_name', models.CharField(help_text="Device identifier (e.g., 'RPi-Truck-1')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Disable key without deleting it')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fillrecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='fill_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('predicted', 'Predicted')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='last_emptied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
