# Generated by Django 5.2.8 on 2025-11-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbageData', '0005_apikey_alter_fillrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='nfc_uid',
            field=models.CharField(blank=True, help_text='NFC tag UID (hardware address)', max_length=50, null=True, unique=True),
        ),
    ]
